apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-service-tests
    app.kubernetes.io/managed-by: kustomize
  name: e2e
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["/metrics", "/logs", "/logs/*"]
  verbs: ["get"]
