apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-service-tests
    app.kubernetes.io/managed-by: kustomize
  name: kubernetes-service-tests
  namespace: system
